name: Continuous Deployment (Raspberry Pi)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Raspberry Pi
    runs-on: self-hosted

    steps:
      - name: Deploy Ecommerce Docker Stack with Fast BuildKit Cache
        run: |
          TARGET_DIR="/srv/dev-disk-by-uuid-168E23328E2309B7/code/project/Ecommerce"
          if [ -d "$TARGET_DIR" ]; then
            cd "$TARGET_DIR"
          else
            cd ~/Ecommerce_docker || cd ~/Ecommerce
          fi
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1
          git pull origin main
          docker compose up --build -d
          docker image prune -f
