name: Continuous Deployment (Raspberry Pi)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Raspberry Pi
    runs-on: self-hosted

    steps:
      - name: Deploy Ecommerce Docker Stack
        run: |
          cd ~/Ecommerce_docker
          git pull origin main
          docker compose down
          docker compose up --build -d
          docker image prune -f
